# Generated by Django 4.0.3 on 2022-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mobNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pass1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pass2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
