# Generated by Django 4.0.3 on 2022-04-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='pass1',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='pass2',
            new_name='password',
        ),
    ]
