# Generated by Django 4.0.3 on 2022-04-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userdata_mobno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='mobNo',
        ),
    ]
