# Generated by Django 4.0.3 on 2022-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userdata_mobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
